<?php
header('Content-Type: application/json');
require_once __DIR__ . '/security.php';
require_once __DIR__ . '/../database/models/QueueModel.php';

secureSessionStart();
requireAuth(['admincashier', 'superadmin']);

try {
    $model = new QueueModel();
    // For walk-ins generated by admin, we use null for user_id
    $result = $model->create(null, null, 'Walk-in Student', 'General Inquiry');
    
    if ($result) {
        $ticket = $model->getById($result['id']);
        echo json_encode(['success' => true, 'ticket' => $ticket]);
    } else {
        throw new Exception("Failed to generate ticket.");
    }
} catch (Exception $e) {
    http_response_code(500);
    echo json_encode(['success' => false, 'error' => $e->getMessage()]);
}
?>